### ISSUE TITLE
Error while npm install

### ISSUE THREAD

**Issue by darkson95** [mecking/inotify-recursive-js#1]
Hi mecking,

unfortunately i am getting errors while I try to install this package with npm. I tried to build it on myself, but I got more errors.
This is what I get when I try "npm install inotify-recursive":
![mintty_2016-10-30_11-55-43](https://cloud.githubusercontent.com/assets/11984325/19836130/dd4c7b5a-9e97-11e6-9518-a4c7cdd86163.png)

The npm-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'inotify' ]
> 2 info using npm@3.10.8
> 3 info using node@v6.9.1
> 4 silly fetchPackageMetaData inotify
> 5 silly fetchNamedPackageData inotify
> 6 silly mapToRegistry name inotify
> 7 silly mapToRegistry using default registry
> 8 silly mapToRegistry registry https://registry.npmjs.org/
> 9 silly mapToRegistry data Result {
> 9 silly mapToRegistry   raw: 'inotify',
> 9 silly mapToRegistry   scope: null,
> 9 silly mapToRegistry   escapedName: 'inotify',
> 9 silly mapToRegistry   name: 'inotify',
> 9 silly mapToRegistry   rawSpec: '',
> 9 silly mapToRegistry   spec: 'latest',
> 9 silly mapToRegistry   type: 'tag' }
> 10 silly mapToRegistry uri https://registry.npmjs.org/inotify
> 11 verbose request uri https://registry.npmjs.org/inotify
> 12 verbose request no auth needed
> 13 info attempt registry request try #1 at 11:57:11 AM
> 14 verbose request id f49eb0bd114bb24d
> 15 verbose etag "2V1LOI5CGQOOFRYZZ7CR6I1W2"
> 16 http request GET https://registry.npmjs.org/inotify
> 17 http 304 https://registry.npmjs.org/inotify
> 18 verbose headers { date: 'Sun, 30 Oct 2016 10:57:11 GMT',
> 18 verbose headers   via: '1.1 varnish',
> 18 verbose headers   'cache-control': 'max-age=300',
> 18 verbose headers   etag: '"2V1LOI5CGQOOFRYZZ7CR6I1W2"',
> 18 verbose headers   age: '0',
> 18 verbose headers   connection: 'keep-alive',
> 18 verbose headers   'x-served-by': 'cache-fra1220-FRA',
> 18 verbose headers   'x-cache': 'HIT',
> 18 verbose headers   'x-cache-hits': '1',
> 18 verbose headers   'x-timer': 'S1477825031.948053,VS0,VE437',
> 18 verbose headers   vary: 'Accept-Encoding' }
> 19 silly get cb [ 304,
> 19 silly get   { date: 'Sun, 30 Oct 2016 10:57:11 GMT',
> 19 silly get     via: '1.1 varnish',
> 19 silly get     'cache-control': 'max-age=300',
> 19 silly get     etag: '"2V1LOI5CGQOOFRYZZ7CR6I1W2"',
> 19 silly get     age: '0',
> 19 silly get     connection: 'keep-alive',
> 19 silly get     'x-served-by': 'cache-fra1220-FRA',
> 19 silly get     'x-cache': 'HIT',
> 19 silly get     'x-cache-hits': '1',
> 19 silly get     'x-timer': 'S1477825031.948053,VS0,VE437',
> 19 silly get     vary: 'Accept-Encoding' } ]
> 20 verbose etag https://registry.npmjs.org/inotify from cache
> 21 verbose get saving inotify to /root/.npm/registry.npmjs.org/inotify/.cache.json
> 22 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
> 23 silly bugs url https://github.com/c4milo/node-inotify/issues
> 24 verbose stack Error: spawn xdg-open ENOENT
> 24 verbose stack     at exports._errnoException (util.js:1026:11)
> 24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 24 verbose stack     at onErrorNT (internal/child_process.js:359:16)
> 24 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> 24 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
> 25 verbose cwd /root/FileBot
> 26 error Linux 3.10.77
> 27 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "inotify"
> 28 error node v6.9.1
> 29 error npm  v3.10.8
> 30 error path xdg-open
> 31 error code ENOENT
> 32 error errno ENOENT
> 33 error syscall spawn xdg-open
> 34 error enoent spawn xdg-open ENOENT
> 35 error enoent spawn xdg-open ENOENT
> 35 error enoent This is most likely not a problem with npm itself
> 35 error enoent and is related to npm not being able to find a file.
> 36 verbose exit [ 1, true ]

darkson95

**Comment by mecking** [comment]
Hi @darkson95 
Can you do a test for me? Please change package.json from "inotify": "~1.2.1"  to "inotify": "~1.4.1".
That's OK in my lab.

**Comment by darkson95** [comment]
Hi @mecking 
I changed the version of inotify in the package.json, but it didn't solve the problem. This is my Output:

![](http://i.imgur.com/UyvTIuA.png)

**Comment by mecking** [comment]
Hi, sorry for long delay... 
 
![image](https://cloud.githubusercontent.com/assets/261325/22182912/32cd9522-e098-11e6-8b54-86b56346d063.png)
That's is OK for me.

**Comment by mecking** [comment]
I published a new version on npm repository
![image](https://cloud.githubusercontent.com/assets/261325/22214963/cc7576c0-e180-11e6-95d8-aec6386c817e.png)
